"""
Per-slot deterministic permutations for binary URA.

Each of the K slots gets a fixed permutation of [0, N) that is
deterministically derived from the slot index. The same permutations
must be used at both encoding (data side) and decoding (model side),
so this utility is the single source of truth — import from both.

Design:
- Permutation k is generated by torch.randperm(N) seeded with (BASE_SEED + k).
- Inverse permutations are precomputed via argsort.
- Both the data pipeline and the model call get_slot_perms(K, N) and get
  bit-identical results, regardless of host RNG state.
"""

import torch

BASE_SEED = 1000


def get_slot_perms(K: int, N: int, base_seed: int = BASE_SEED) -> torch.Tensor:
    """Return [K, N] tensor where row k is the permutation for slot k.

    Convention: slot k transmits c_k[n] at channel use slot_perms[k, n].
    Equivalently, channel use j carries slot k's bit at LDPC position
    slot_perms_inv[k, j].
    """
    perms = []
    for k in range(K):
        g = torch.Generator().manual_seed(base_seed + k)
        perms.append(torch.randperm(N, generator=g))
    return torch.stack(perms)  # [K, N], dtype=long


def get_slot_perms_inv(K: int, N: int, base_seed: int = BASE_SEED) -> torch.Tensor:
    """Return [K, N] inverse permutations matching get_slot_perms(K, N)."""
    perms = get_slot_perms(K, N, base_seed)
    return torch.argsort(perms, dim=-1)  # [K, N], dtype=long


def get_slot_perms_pair(
    K: int, N: int, base_seed: int = BASE_SEED
) -> tuple[torch.Tensor, torch.Tensor]:
    """Return (slot_perms, slot_perms_inv) — both [K, N], both long."""
    perms = get_slot_perms(K, N, base_seed)
    perms_inv = torch.argsort(perms, dim=-1)
    return perms, perms_inv
